#!/usr/bin/env python3
"""
Generate art prompts for all 236 pets in v3 design.
Output: 宠物美术资源提示词v3.md
Each pet gets 4 prompts: normal_avatar, normal_full, awakened_avatar, awakened_full
"""
import os, json

OUTPUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "宠物美术资源提示词v3.md")

# ─── Shared style blocks ───
S_AV = (
    "chibi 2D Chinese ink wash painting game character icon, super deformed cute style, "
    "big head small body ratio 2:1, Chinese calligraphy brush-style black ink outlines with varying thickness "
    "and expressive brush stroke feel, ink wash coloring with subtle tonal gradation and soft layered shading "
    "to create gentle volume and three-dimensional depth, light and shadow rendered through ink density variation "
    "— lighter wash on highlighted areas and denser ink in recessed folds and under the chin and belly, "
    "rich varied color palette mixing traditional Chinese mineral pigments with natural animal tones, "
    "Chinese Xianxia mythology aesthetic, NOT Western fantasy, NOT realistic, NOT 3D rendered, "
    "square 1:1 aspect ratio, close-up showing oversized head and upper shoulders, "
    "solid plain single-color background light gray #E0E0E0, expressive ink-painted eyes with reflective highlights, "
    "game icon style, clean sharp ink-line edges for easy cutout."
)
S_FL = S_AV.replace("game character icon,", "game character,").replace(
    "square 1:1 aspect ratio, close-up showing oversized head and upper shoulders,",
    "full body view front-facing centered on canvas,"
).replace("and under the chin and belly,", "and under limbs,").replace(
    "game icon style,", "game asset style,"
)
S_AA = (
    "chibi 2D Chinese ink wash painting game character icon, super deformed cute style, "
    "big head small body ratio 2:1, Chinese calligraphy brush-style black ink outlines with varying thickness "
    "and expressive brush stroke feel, ink wash coloring with subtle tonal gradation and soft layered shading "
    "to create gentle volume and three-dimensional depth, light and shadow rendered through ink density variation "
    "— lighter wash on highlighted areas and denser ink in recessed folds creating natural cel-shaded dimensionality, "
    "rich varied color palette mixing traditional Chinese mineral pigments with natural and warm tones, "
    "Chinese Xianxia mythology aesthetic with ornate accessories and flowing ribbons, "
    "NOT Western fantasy, NOT realistic, NOT 3D rendered, "
    "square 1:1 aspect ratio, close-up showing oversized head and upper shoulders, "
    "solid plain single-color background light gray #E0E0E0, expressive ink-painted eyes with reflective highlights, "
    "game icon style, clean sharp ink-line edges for easy cutout, "
    "more refined details and ornate accessories than base version, golden star-rank accents on key accessories."
)
S_AF = S_AA.replace("game character icon,", "game character,").replace(
    "square 1:1 aspect ratio, close-up showing oversized head and upper shoulders,",
    "full body view front-facing centered on canvas,"
).replace("game icon style,", "game asset style,")

F_N = (
    "STRICTLY FORBIDDEN: any text, letters, characters, words, writing, labels, captions, watermark, signature, "
    "runes, sigils, symbols, glyphs, seals, calligraphy marks, Daoist script, mystical writing, floating characters, "
    "icon overlays, any mark that resembles text or written language. "
    "STRICTLY FORBIDDEN: white outline outside black ink outlines, white border around character, white edge glow, "
    "white halo, any white fringe between character outline and background. "
    "The black ink outline must be the absolute outermost edge directly touching the background with zero gap. "
    "Also forbidden: glow effects, blur, soft edges, lighting effects. "
    "This is the NORMAL base form (not evolved)."
)
F_A = F_N.replace(
    "any mark that resembles text or written language.",
    "any mark that resembles text or written language, "
    "any floating decorative elements that look like script or language."
).replace(
    "This is the NORMAL base form (not evolved).",
    "This is the AWAKENED max-star evolved form."
)

R_AV = "Resolution: 128x128px target, circular crop friendly composition."
R_FL = "Resolution: 512x512px target, the character should fill about 70-80% of the canvas height."

# ─── Pet data: (num, cn_name, pet_id, rarity, element, race, creature_en,
#     normal_av_desc, normal_full_desc, awaken_av_desc, awaken_full_desc) ───
# Each desc is JUST the character-specific part (no style prefix, no forbidden, no resolution)

PETS = [
# ════════════════════════════════════════
# 兽灵族 基础 (16)
# ════════════════════════════════════════
(1,"炎狐","flame_fox","R","火","兽灵族","fox spirit kit",
"A young fox spirit kit, warm cream and soft peach body fur with ink wash brush texture showing volume through tonal shading, bright amber-orange ear tips fading from the cream base, a small fluffy tail with the very tip glowing ember-orange suggesting warmth, large sparkling teal-green eyes with a curious lively expression, tiny coral-red silk ribbon tied in a bow at the neck, rosy pink inner ears, subtle warm shadow under the chin and on the belly giving roundness and depth.",
"A young fox spirit kit in battle-ready stance, warm cream and soft peach body fur with flowing ink wash brush strokes showing volume through tonal variation, bright amber-orange ear tips and paw tips contrasting the cream body, a single fluffy tail raised high with the tip glowing ember-orange like a small flame, large sparkling teal-green eyes with sharp determined battle gaze, tiny coral-red silk ribbon collar fluttering, front paws spread in a low combat stance ready to pounce, body slightly crouched and leaning forward, mouth slightly open showing tiny fangs in a fierce cute growl, rosy pink inner ears, subtle warm shadows under the belly and between the legs giving roundness and depth, energetic feisty expression.",
"A majestic young fox spirit in evolved form, luxurious cream-white and warm amber fur with flowing ink wash brush texture and rich tonal shading showing volume, vivid golden-orange flame patterns along the cheeks like elegant war paint, large blazing teal-green eyes with a golden star-shaped ring in the pupil radiating fierce battle spirit, pointed ears tipped with fiery vermilion-red and adorned with tiny golden bell earrings, an ornate small red jade pendant with golden filigree hanging at the neck on a crimson braided cord, intense proud warrior expression, bushy dual tails visible behind — cream base with brilliant sunset-orange and vermilion tips, subtle warm depth shadows under chin and around the ornaments.",
"in dynamic battle pose. A majestic young fox spirit in evolved form mid-attack, luxurious cream-white and warm amber fur with flowing ink wash brush strokes and rich tonal shading showing volume and depth, vivid golden-orange flame patterns along the body like elegant war markings, large blazing teal-green eyes with a golden star-shaped ring radiating fierce battle spirit, pointed ears tipped with fiery vermilion-red and adorned with tiny golden bell earrings angled back aggressively, an ornate small red jade pendant with golden filigree swinging with movement on a crimson braided cord, dynamic leaping attack pose with one front paw swiping forward showing tiny claws, body twisting mid-strike with powerful momentum, magnificent dual tails fanned out behind — cream base flowing into brilliant sunset-orange and vermilion tips like twin flames, mouth open in a battle cry showing fangs, intense warrior expression mixing cunning and ferocity, subtle warm depth shadows under the belly and between limbs enhancing three-dimensionality."),

(2,"溪獭","brook_otter","R","水","兽灵族","otter spirit",
"A young otter spirit, soft brown and warm chocolate body fur with lighter creamy-beige chest and belly, ink wash brush texture showing volume through tonal shading, gentle teal-blue streaks in the fur along the sides resembling flowing water ripples, large round sparkling dark-brown eyes with a playful cheerful expression, a tiny aquamarine gemstone bead on a simple cord around the neck, little whiskers, smooth streamlined head shape, subtle cool shadows under the chin giving depth and roundness.",
"A young otter spirit in playful battle stance, soft brown and warm chocolate body fur with lighter creamy-beige belly and chest, ink wash brush strokes showing volume through tonal variation, gentle teal-blue streaks along the body like flowing water patterns, large round sparkling dark-brown eyes with alert determined gaze, a tiny aquamarine gemstone bead on a simple cord around the neck, standing on hind legs with front paws raised in a ready-to-splash pose, a sleek thick tail with the tip showing cool blue-green water sheen, little whiskers, webbed paw details, playful yet battle-ready expression with a small grin, subtle cool shadows under the belly and between the limbs giving depth.",
"A majestic evolved otter spirit, luxurious deep chocolate-brown and rich teal fur with flowing ink wash texture, intricate swirling water-current patterns in cerulean and silver along the cheeks and forehead like flowing tattoos, large sparkling dark-brown eyes with a sapphire-blue ring in the pupil radiating water mastery, rounded ears adorned with tiny silver droplet earrings, an ornate turquoise jade pendant on a woven blue-silver cord at the neck, confident wise expression, a regal mane-like tuft of fur at the nape flowing with watery sheen, subtle cool depth shadows under the chin and around the ornaments.",
"in dynamic battle pose. A majestic evolved otter spirit mid-attack, luxurious deep chocolate-brown and rich teal fur with flowing ink wash brush strokes and rich tonal depth, intricate swirling water-current patterns in cerulean and silver along the body, large sparkling dark-brown eyes with sapphire-blue ring radiating fierce water mastery, rounded ears adorned with tiny silver droplet earrings angled back, an ornate turquoise jade pendant swinging with movement on a woven blue-silver cord, dynamic lunging pose with front paws striking forward creating visible water splash effect, a magnificent thick tail raised high with shimmering teal-blue tip, body twisting with fluid grace, mouth open in a battle cry, confident powerful expression, subtle cool depth shadows enhancing three-dimensionality."),

(3,"叶鹿","leaf_deer","R","草","兽灵族","deer spirit fawn",
"A young deer spirit fawn, soft warm fawn-brown body fur with lighter cream spots on the back, ink wash brush texture showing volume through tonal shading, small budding antlers with tiny green leaf sprouts growing from the tips, large gentle dark-amber eyes with a shy curious expression, a delicate pale-green vine with a tiny flower bud loosely wrapped around one antler, soft pink nose, light emerald-green highlights at the ear tips, subtle warm shadow under the chin and on the neck giving roundness and depth.",
"A young deer spirit fawn in alert battle stance, soft warm fawn-brown body fur with lighter cream spots, ink wash brush strokes showing volume through tonal variation, small budding antlers with tiny green leaf sprouts growing from the tips, large gentle dark-amber eyes with sharp alert gaze, a delicate pale-green vine with a tiny flower loosely around one antler, slender legs in a ready-to-spring pose, body slightly lowered with weight on the back legs ready to leap, a short fluffy tail, soft pink nose, light emerald-green highlights at the ear tips and hoof edges, subtle warm shadows under the belly giving depth, nimble graceful expression.",
"A majestic evolved deer spirit, luxurious golden-fawn and rich cream fur with flowing ink wash texture, magnificent branching antlers covered in lush green leaves and small pink blossoms like a miniature tree crown, large gentle dark-amber eyes with an emerald-green ring in the pupil radiating nature's power, delicate golden leaf-shaped ornaments dangling from the antler branches, a small jade-green gemstone pendant on a braided vine cord at the neck, serene yet powerful expression, soft golden-green glow reflected on the face from the antler foliage, subtle warm depth shadows under the chin and around the ornaments.",
"in dynamic battle pose. A majestic evolved deer spirit mid-charge, luxurious golden-fawn and rich cream fur with flowing ink wash brush strokes and rich tonal depth, magnificent branching antlers covered in lush green leaves and blooming pink flowers swaying with motion, large gentle dark-amber eyes with emerald-green ring blazing with nature's fury, delicate golden leaf-shaped ornaments swinging from the antler branches, a jade-green gemstone pendant bouncing on a braided vine cord, dynamic charging pose with head lowered and antlers pointed forward, front hooves kicking up, body surging with powerful momentum, leaves scattering from the antlers with the charge, fierce determined expression mixed with grace, subtle warm depth shadows enhancing three-dimensionality."),

(4,"岩獾","rock_badger","R","土","兽灵族","badger spirit",
"A young badger spirit, stout body with dark charcoal-brown fur on top and lighter sandy-cream on the belly, ink wash brush texture showing volume through tonal shading, distinctive cream and dark face stripes characteristic of a badger, rough rocky-textured patches on the back and shoulders like natural stone armor, large round determined dark eyes with a stubborn tenacious expression, tiny rugged stone-colored nose, small rounded ears with dusty-brown tips, a faint amber-orange glow at the edges of the rocky patches suggesting earth energy, subtle warm shadow under the chin giving depth.",
"A young badger spirit in defensive battle stance, stout body with dark charcoal-brown fur on top and lighter sandy-cream belly, ink wash brush strokes showing volume through tonal variation, distinctive cream and dark face stripes, rough rocky-textured armor patches along the back and shoulders, large round determined dark eyes with fierce defensive glare, standing low to the ground with front claws dug in, stocky powerful stance with weight centered, short thick tail, tiny rugged nose, faint amber-orange glow at rocky patch edges, muscles tensed in a ready-to-dig-and-strike pose, tough unwavering expression, subtle warm shadows under the belly and between the sturdy legs.",
"A majestic evolved badger spirit, powerful stout form with deep slate-gray and warm earth-brown fur with flowing ink wash texture, magnificent crystalline rock formations growing from the back like a mountain ridge in warm amber and brown tones, large fierce dark eyes with a topaz-gold ring in the pupil radiating earth mastery, distinctive face stripes now with golden highlights, small stone-carved earrings shaped like mountains, an ornate amber gemstone pendant set in rough stone housing on a leather cord, indomitable warrior expression, subtle warm depth shadows under the chin and around the crystalline formations.",
"in dynamic battle pose. A majestic evolved badger spirit mid-ground-slam, powerful stout form with deep slate-gray and warm earth-brown fur, magnificent crystalline rock formations on the back glowing with amber earth energy, large fierce dark eyes with topaz-gold ring blazing with earth power, distinctive face stripes with golden highlights, small stone-carved mountain earrings, amber gemstone pendant swinging on leather cord, dynamic ground-pound pose with both front paws slamming downward, cracks and stone debris flying up from the impact point, stocky body coiled with devastating power, mouth open showing sturdy teeth in a fierce battle roar, indomitable expression, subtle warm depth shadows enhancing three-dimensionality."),

(5,"风鼬","gale_weasel","R","风","兽灵族","weasel spirit",
"A young weasel spirit, sleek elongated body with silvery-white fur and soft lavender undertones, ink wash brush texture showing volume through tonal shading, incredibly fluffy tail that seems to trail wisps of wind, large bright violet-blue eyes with an alert mischievous expression, small pointed ears with pale silver tips, a tiny sky-blue bead on a thin cord around the neck, slender pointed snout with a pink nose, fur swept back as if constantly blown by wind, subtle cool shadows under the chin giving depth and sleekness.",
"A young weasel spirit in agile battle stance, sleek elongated body with silvery-white fur and soft lavender undertones, ink wash brush strokes showing volume through tonal variation, incredibly fluffy windswept tail trailing behind, large bright violet-blue eyes with sharp alert gaze, small pointed ears swept back, a tiny sky-blue bead on a thin cord around the neck, slender body in a dynamic mid-sprint pose, front paws barely touching the ground suggesting incredible speed, body stretched long and low like an arrow, fur streaming backward from velocity, playful cocky grin, subtle cool shadows along the sleek body enhancing speed impression.",
"A majestic evolved weasel spirit, sleek form with luminous pearl-white and soft silver-violet fur with flowing ink wash texture, elegant wind-spiral patterns along the cheeks in pale cyan and silver, large blazing violet-blue eyes with a diamond-white ring in the pupil radiating wind mastery, pointed ears adorned with tiny silver wind-chime earrings, an ornate pale sapphire pendant in silver filigree on a silk cord at the neck, confident swift warrior expression, magnificent plume-like tail with silver and pale cyan tips flowing like a wind stream, subtle cool depth shadows under the chin and around the ornaments.",
"in dynamic battle pose. A majestic evolved weasel spirit mid-dash attack, sleek form with luminous pearl-white and soft silver-violet fur, elegant wind-spiral patterns along the body in pale cyan and silver, large blazing violet-blue eyes with diamond-white ring, pointed ears with silver wind-chime earrings swept back by speed, pale sapphire pendant trailing behind on silk cord, dynamic blurring-speed attack pose, body stretched in a lightning-fast strike with one paw slashing forward, magnificent tail stretched behind like a comet trail in silver and pale cyan, afterimage effect suggesting impossible speed, fierce exhilarated expression, subtle cool depth shadows enhancing three-dimensionality."),

(6,"雷貂","thunder_marten","R","雷","兽灵族","marten spirit",
"A young marten spirit, sleek body with dark chocolate-brown fur and bright golden-yellow lightning-bolt-shaped streaks along the sides, ink wash brush texture showing volume through tonal shading, fluffy chest bib in warm cream-yellow, large alert golden-amber eyes with an energetic sparky expression, small rounded ears with golden-yellow tips, fur slightly standing on end from static electricity, a tiny amber crystal bead on a cord around the neck, pointed snout with dark nose, subtle warm shadow under the chin giving depth.",
"A young marten spirit in electrified battle stance, sleek body with dark chocolate-brown fur and bright golden-yellow streaks along the sides, ink wash brush strokes showing volume, fluffy cream-yellow chest bib, large alert golden-amber eyes with fierce determined gaze, fur standing on end crackling with tiny static sparks, small rounded ears with golden-yellow tips, standing on hind legs with front paws raised showing tiny claws sparking, body coiled and ready to strike, bushy tail raised with golden-yellow tip, pointed snout open showing teeth, energetic aggressive expression, subtle warm shadows under the belly.",
"A majestic evolved marten spirit, powerful form with deep mahogany-brown and blazing gold fur with flowing ink wash texture, dramatic golden-yellow lightning patterns across the face and forehead, large fierce golden-amber eyes with an electric-yellow ring in the pupil radiating thunder power, pointed ears adorned with tiny gold thunderbolt-shaped earrings, a magnificent ruff of golden-tipped fur around the neck like a mane, an ornate citrine gemstone pendant in bronze setting on a braided cord, intense electrifying warrior expression, subtle warm depth shadows under the chin and around the ornaments.",
"in dynamic battle pose. A majestic evolved marten spirit mid-lightning-strike, powerful form with deep mahogany-brown and blazing gold fur, dramatic golden-yellow lightning patterns across the body, large fierce golden-amber eyes with electric-yellow ring blazing, pointed ears with gold thunderbolt earrings angled back, citrine gemstone pendant swinging, dynamic leaping attack pose with both front paws crackling with electrical energy, body arched mid-strike, magnificent bushy tail fully electrified with golden-yellow sparks flying, mouth open in a fierce crackling battle cry, intense thunderous expression, subtle warm depth shadows enhancing three-dimensionality."),

(7,"刺猬","thorn_hedgehog","R","草","兽灵族","hedgehog spirit",
"A young hedgehog spirit, round chubby body with warm brown belly fur and a back covered in dark green thorny vine-like spines instead of regular quills, ink wash brush texture showing volume through tonal shading, tiny leaves and buds sprouting from some spines, large round sparkling dark-green eyes with a timid but determined expression, small pink nose, little pink paws, rosy blush on the cheeks, a tiny seed-shaped wooden bead on a thin vine cord around the neck, subtle warm shadow under the round belly giving adorable depth.",
"A young hedgehog spirit in defensive battle stance, round chubby body with warm brown belly fur and dark green thorny vine spines on the back, ink wash brush strokes showing volume, tiny leaves and buds sprouting from spines, large round sparkling dark-green eyes with determined defensive glare, curled slightly into a ball exposing the thorny spines outward, small pink nose, little pink paws planted firmly, body low and round in a defensive pose, ready to charge forward like a spiky ball, cute fierce expression, subtle warm shadows under the round body giving depth.",
"A majestic evolved hedgehog spirit, round powerful form with rich warm brown belly and magnificent thorny vine spines now blooming with small colorful flowers in pink, white, and yellow, flowing ink wash texture, large fierce dark-green eyes with an emerald ring in the pupil radiating plant mastery, small ears adorned with tiny flower bud earrings, thorns now longer and sharper with golden tips, an ornate small green jade acorn pendant on a braided vine cord, proud fierce expression despite the cute round shape, subtle warm depth shadows under the chin and around the flowering spines.",
"in dynamic battle pose. A majestic evolved hedgehog spirit mid-rolling-charge, round powerful form with rich warm brown belly and magnificent blooming thorny vine spines with colorful flowers, large fierce dark-green eyes with emerald ring blazing, tiny flower bud earrings, thorns with golden tips, jade acorn pendant bouncing, dynamic spinning charge pose — curled into a devastating rolling ball of thorns and flowers, vine tendrils extending outward from the spin, petals and leaves scattering from the rotation, fierce battle roar expression, powerful momentum implied by motion lines, subtle warm depth shadows enhancing three-dimensionality."),

(8,"赤狼","crimson_wolf","R","火","兽灵族","wolf spirit",
"A young wolf spirit, lean body with deep dusky-red and dark charcoal fur, ink wash brush texture showing volume through tonal shading, a wild rugged mane of dark crimson fur around the neck, large intense amber-red eyes with flickering flame reflections in the pupils giving a dangerous gaze, pointed wolf ears with dark tips, a jagged scar-like pattern in lighter red across one cheek, small sharp fangs slightly visible, rough and feral appearance contrasting with the cute chibi style, subtle warm shadow under the chin giving depth and menace.",
"A young wolf spirit in aggressive battle stance, lean body with deep dusky-red and dark charcoal fur, ink wash brush strokes showing volume, wild rugged crimson mane around the neck, large intense amber-red eyes with flame reflections giving dangerous gaze, pointed wolf ears laid back aggressively, a jagged scar-like pattern in lighter red across one cheek, standing in a low aggressive crouch, hackles raised, a bushy dark-tipped tail held straight out, mouth open showing sharp fangs in a snarl, front paws spread wide in predatory stance, lone-wolf fierce expression, subtle warm shadows under the belly and along the lean body.",
"A majestic evolved wolf spirit, powerful lean form with deep crimson and dark ember fur with flowing ink wash texture, dramatic fire-like patterns along the cheeks and forehead in bright vermilion and gold, large blazing amber-red eyes with a crimson flame ring in the pupil radiating fire mastery, pointed ears adorned with dark iron fang-shaped earrings, a rugged iron pendant with a red gemstone center on a leather cord at the neck, wild crimson mane now longer and flame-like, intense apex predator expression, subtle warm depth shadows under the chin giving menacing depth.",
"in dynamic battle pose. A majestic evolved wolf spirit mid-pounce attack, powerful lean form with deep crimson and dark ember fur, dramatic fire-like patterns along the body in bright vermilion and gold, large blazing amber-red eyes with crimson flame ring, pointed ears with dark iron fang earrings pinned back, iron pendant with red gemstone swinging, dynamic lunging attack pose with jaws wide open showing razor fangs, wild crimson flame-like mane streaming backward, bushy tail blazing with ember-red tips, body fully extended in a savage pounce, claws extended, intense feral battle fury expression, subtle warm depth shadows enhancing three-dimensionality."),

(9,"铁甲犰狳","iron_armadillo","R","土","兽灵族","armadillo spirit",
"A young armadillo spirit, round compact body with iron-gray metallic shell plates and a soft peach-beige underbelly, ink wash brush texture showing volume through tonal shading, the armored plates have a subtle metallic sheen rendered through ink wash highlights, large round curious dark eyes peeking out from under the head plate, small pointed ears, a tiny copper-colored rivet bead on a cord around the neck, short snout with a dark nose, cute and sturdy appearance, subtle cool shadow under the shell plates giving depth and a three-dimensional armored look.",
"A young armadillo spirit in defensive battle stance, round compact body with iron-gray metallic shell plates and soft peach-beige underbelly, ink wash brush strokes showing volume, metallic sheen on armor plates through ink wash highlights, large round curious dark eyes with determined gaze, curled slightly showing the armored shell, standing with short sturdy legs firmly planted, a short thick armored tail, small pointed ears, copper rivet bead at neck, ready to roll into a ball or charge forward, stocky unbreakable defensive pose, subtle cool shadows under the shell enhancing the armored depth.",
"A majestic evolved armadillo spirit, powerful round form with polished dark steel and warm bronze armor plates with flowing ink wash texture, intricate geometric patterns etched into the plates in golden lines, large fierce dark eyes with a steel-blue ring in the pupil radiating iron defense mastery, small ears adorned with tiny gear-shaped bronze earrings, an ornate iron shield-shaped pendant with a citrine gem center on a chain at the neck, plates now multi-layered and more elaborate, proud impenetrable fortress expression, subtle metallic depth shadows under the chin and between the armor plates.",
"in dynamic battle pose. A majestic evolved armadillo spirit mid-rolling-charge attack, powerful round form with polished dark steel and warm bronze armor plates, golden geometric patterns etched into the plates, large fierce dark eyes with steel-blue ring blazing, gear-shaped bronze earrings, iron shield pendant bouncing, dynamic rolling attack pose — curled into a devastating armored ball of steel and bronze, spinning with incredible force, metal sparks flying from the impact, golden etchings glowing with earth energy, fierce unstoppable expression visible through the curl, subtle metallic depth shadows enhancing three-dimensionality."),

(10,"云豹","cloud_leopard","R","风","兽灵族","snow leopard spirit",
"A young snow leopard spirit, soft thick fur in pale silver-white with subtle gray rosette markings that have a cloud-like wispy quality, ink wash brush texture showing volume through tonal shading, large calm ice-blue eyes with a serene mysterious expression, small rounded ears with silver tips, a fluffy thick tail curling around, a tiny pale-blue crystal bead on a silk cord around the neck, pink nose, whiskers, elegant and ethereal appearance, subtle cool shadow under the chin giving depth and softness.",
"A young snow leopard spirit in graceful battle stance, soft thick fur in pale silver-white with subtle gray cloud-like rosette markings, ink wash brush strokes showing volume, large calm ice-blue eyes with sharp focused gaze, small rounded ears, standing in an elegant low crouch ready to spring, a magnificent long thick fluffy tail with silver-gray tip curving behind, a pale-blue crystal bead at the neck, slender powerful legs, body lithe and poised, one front paw slightly raised, wisps of mist seemingly trailing from the fur, serene yet deadly expression, subtle cool shadows under the belly and along the graceful form.",
"A majestic evolved snow leopard spirit, luxurious pearl-white and soft silver fur with flowing ink wash texture, cloud-like rosette markings now edged with pale cyan wind energy, large piercing ice-blue eyes with a diamond-white ring in the pupil radiating wind mastery, elegant pointed ears adorned with tiny silver cloud-shaped earrings, a magnificent silver-white mane around the neck like a cloud collar, an ornate moonstone pendant in silver filigree on a silk cord, regal ethereal expression, subtle cool depth shadows giving mystical depth.",
"in dynamic battle pose. A majestic evolved snow leopard spirit mid-leap attack, luxurious pearl-white and soft silver fur, cloud-like rosette markings edged with pale cyan wind energy, large piercing ice-blue eyes with diamond-white ring, silver cloud-shaped earrings trailing behind, moonstone pendant swinging, dynamic aerial strike pose with body fully stretched in a gravity-defying leap, one paw swiping with razor precision, magnificent long fluffy tail streaming behind like a cloud trail, wisps of wind and mist swirling around the body, silent deadly grace in motion, subtle cool depth shadows enhancing three-dimensionality."),

(11,"焰狮","blaze_lion","SR","火","兽灵族","lion spirit",
"A young lion spirit, warm golden-tawny body fur with darker brown shading, ink wash brush texture showing volume through tonal shading, a magnificent small mane of fiery copper-red and warm orange around the head and neck resembling flickering flames, large proud golden-amber eyes with a regal commanding expression, strong jaw, small tufted ears poking through the mane, a sturdy crimson cord with a gold bead at the neck, subtle warm shadow under the mane giving fiery depth.",
"A young lion spirit in powerful battle stance, warm golden-tawny body fur with darker brown shading, ink wash brush strokes showing volume, magnificent fiery copper-red and warm orange mane around the head, large proud golden-amber eyes with fierce battle gaze, standing tall and broad with front paws spread wide, muscular forelegs, a tufted tail with a bright orange-red flame-like tip raised high, mouth open in a fierce roar showing fangs, strong regal posture radiating confidence, subtle warm shadows under the barrel chest giving powerful depth.",
"A majestic evolved lion spirit, powerful form with rich golden and warm bronze fur with flowing ink wash texture, magnificent blazing mane now a corona of deep crimson, bright orange, and golden flames, large blazing golden-amber eyes with a sun-gold ring in the pupil radiating fire sovereignty, strong jaw adorned with a golden chain, small tufted ears with golden flame-tip ornaments, an ornate golden sun medallion pendant on a thick crimson cord, absolute king of beasts expression, subtle warm fiery depth shadows under the blazing mane.",
"in dynamic battle pose. A majestic evolved lion spirit mid-roar attack, powerful form with rich golden and warm bronze fur, magnificent blazing mane erupting in deep crimson, orange, and golden flames, large blazing golden-amber eyes with sun-gold ring, golden chain jaw ornament, golden flame-tip ear ornaments, golden sun medallion swinging, dynamic rearing pose with front paws raised high slamming down with devastating force, mane fully ablaze and spreading outward, tufted tail flaring with intense orange-red fire, mouth wide open in an earth-shaking battle roar, absolute sovereign fury, subtle warm depth shadows enhancing three-dimensionality."),

(12,"冰貉","frost_raccoon","SR","水","兽灵族","raccoon-dog spirit",
"A young raccoon-dog spirit, round fluffy body with soft ice-blue and silvery-white fur, ink wash brush texture showing volume through tonal shading, characteristic dark mask markings around the eyes in deep navy-blue, large round curious sapphire-blue eyes peering through the mask with a cheeky cold expression, round ears with frosted white tips, fluffy cheeks, a tiny ice-blue crystal bead on a thin silver cord around the neck, visible frosty breath near the mouth, subtle cool shadow under the fluffy cheeks giving roundness.",
"A young raccoon-dog spirit in chilly battle stance, round fluffy body with soft ice-blue and silvery-white fur, ink wash brush strokes showing volume, dark navy-blue eye mask markings, large round sapphire-blue eyes with alert gaze, round frosted ears, standing on all fours with fur puffed up from cold energy, a bushy tail with icy-white tip, visible frosty breath, front paws showing tiny frost crystals on the claws, ice-blue crystal bead at neck, puffy winter-ready body shape, mischievous cold warrior expression, subtle cool shadows under the fluffy belly.",
"A majestic evolved raccoon-dog spirit, luxurious deep ice-blue and sparkling frost-white fur with flowing ink wash texture, elaborate frost crystal patterns along the mask and cheeks in shimmering silver and pale cyan, large piercing sapphire-blue eyes with a frost-white ring in the pupil radiating ice mastery, round ears adorned with tiny ice crystal drop earrings, an ornate sapphire pendant in silver snowflake filigree on a fine chain, magnificent fluffy frost ruff around the neck, confident frosty sovereign expression, subtle cool depth shadows.",
"in dynamic battle pose. A majestic evolved raccoon-dog spirit mid-frost-blast attack, luxurious deep ice-blue and sparkling frost-white fur, elaborate frost crystal patterns along the body, large piercing sapphire-blue eyes with frost-white ring, ice crystal drop earrings, sapphire snowflake pendant swinging, dynamic frost breath attack pose with mouth wide open exhaling a cone of visible icy mist, front paws raised with frost crystals forming around them, magnificent bushy tail with crystalline ice formations at the tip, body leaning forward in a powerful frost offensive, fierce freezing expression, subtle cool depth shadows enhancing three-dimensionality."),

(13,"翠蜥","jade_lizard","SR","草","兽灵族","lizard spirit",
"A young lizard spirit, sleek body with rich jade-green scales and warm golden-brown underbelly, ink wash brush texture showing volume through tonal shading, patches of soft moss and tiny fern fronds growing along the back and head ridge, large alert golden-green eyes with slit pupils and an intelligent curious expression, a small head crest of emerald-green leaf-like scales, a tiny green jade bead on a vine cord at the neck, delicate scale patterns rendered with ink wash brush detail, subtle warm shadow under the chin giving reptilian depth.",
"A young lizard spirit in agile battle stance, sleek body with rich jade-green scales and golden-brown underbelly, ink wash brush strokes showing volume, patches of moss and tiny ferns on the back, large alert golden-green slit-pupil eyes with battle focus, small leaf-like head crest raised, low crawling stance with body close to ground, long tail with moss-covered tip curving upward, front claws gripping the surface ready to lunge, tongue slightly flickering, agile and dangerous despite small size, subtle warm shadows under the belly.",
"A majestic evolved lizard spirit, powerful sleek form with deep emerald-green and rich jade scales with flowing ink wash texture, magnificent moss and blooming flower garden growing along the back and head crest, large blazing golden-green eyes with an emerald ring in the slit pupil radiating nature mastery, leaf-like crest now taller and adorned with tiny golden flower ornaments, an ornate jade pendant carved like a leaf in gold filigree on a vine cord, moss-covered scales with tiny blooming flowers, wise ancient forest guardian expression, subtle warm depth shadows.",
"in dynamic battle pose. A majestic evolved lizard spirit mid-tail-whip attack, powerful form with deep emerald-green and jade scales, magnificent blooming garden on the back, large blazing golden-green eyes with emerald ring, golden flower crest ornaments, jade leaf pendant swinging, dynamic tail-whip attack with the long moss-covered tail sweeping in a wide arc scattering petals and leaves, body twisting with reptilian agility, front claws extended, mouth open showing teeth, a wave of green energy trailing the tail strike, fierce forest guardian expression, subtle warm depth shadows enhancing three-dimensionality."),

(14,"磐牛","boulder_ox","SR","土","兽灵族","ox spirit",
"A young ox spirit, massive stout body with deep brown fur and lighter sandy underbelly, ink wash brush texture showing volume through tonal shading, enormous horns made of solid rough stone with amber veins running through them, large calm deep-brown eyes with an immovable steadfast expression, broad flat nose, small ears partially hidden behind the massive stone horns, a sturdy leather cord with a rough-cut amber stone bead at the neck, thick muscular neck, subtle warm shadow under the broad head giving imposing depth.",
"A young ox spirit in immovable battle stance, massive stout body with deep brown fur and lighter sandy underbelly, ink wash brush strokes showing volume, enormous stone horns with amber veins, large calm deep-brown eyes with unwavering defensive gaze, standing absolutely solid and unmovable, four thick sturdy legs planted like pillars, broad muscular shoulders, short thick tail, leather cord with amber stone bead, body radiating pure mass and stability, ground seemingly compressed under the weight, stoic unbreakable expression, subtle warm shadows under the massive body.",
"A majestic evolved ox spirit, colossal stout form with rich earth-brown and warm bronze fur with flowing ink wash texture, magnificent stone horns now larger with golden amber veins and crystalline formations at the tips, large fierce deep-brown eyes with an amber-gold ring in the pupil radiating earth sovereignty, broad forehead with a golden stone seal ornament between the horns, small ears adorned with rough-hewn golden earrings, an ornate large amber pendant in bronze casing on a thick chain, mountain-like immovable sovereign expression, subtle warm depth shadows.",
"in dynamic battle pose. A majestic evolved ox spirit mid-charge, colossal stout form with rich earth-brown and warm bronze fur, magnificent crystal-tipped stone horns with golden amber veins lowered for impact, large fierce deep-brown eyes with amber-gold ring blazing, golden stone seal between horns, golden earrings, amber pendant bouncing on thick chain, dynamic charging pose with head lowered and horns pointed forward, massive body surging with unstoppable momentum, ground cracking beneath the hooves, dust and stone debris flying, devastating freight-train force, absolute power expression, subtle warm depth shadows enhancing three-dimensionality."),

(15,"雷虎","storm_tiger","SR","雷","兽灵族","tiger spirit",
"A young tiger spirit, powerful body with striking white fur and bold black ink-brush-style stripes, ink wash brush texture showing volume through tonal shading, golden-yellow electric highlights along the stripe edges, large fierce amber-gold eyes crackling with electrical energy, strong jaw, rounded ears with black tips and golden-yellow inner glow, a tiny golden lightning-bolt shaped bead on a dark cord at the neck, visible tiny sparks dancing around the whiskers, powerful intense expression, subtle warm shadow under the broad chin giving imposing depth.",
"A young tiger spirit in electrifying battle stance, powerful body with striking white fur and bold black stripes with golden-yellow electric edges, ink wash brush strokes showing volume, large fierce amber-gold eyes crackling with power, rounded ears with electric inner glow, standing in a powerful wide stance, muscular forelegs spread, thick tail with golden-yellow tip raised and crackling with sparks, mouth open in a thunderous roar showing large fangs, golden lightning bead at neck, body radiating electrical energy, fur slightly standing from static, dominant predator expression, subtle warm shadows under the powerful body.",
"A majestic evolved tiger spirit, immense powerful form with pristine white and silver fur with flowing ink wash texture, bold black stripes now edged with blazing electric-gold and crackling with visible lightning, large blazing amber-gold eyes with an electric-white ring in the pupil radiating absolute thunder authority, powerful jaw adorned with golden thunder fang ornaments, ears with golden arc-shaped earrings, an ornate golden thunderbolt medallion pendant on a thick dark chain, magnificent electric mane of golden-tipped fur around the neck, supreme thunder king expression, subtle warm electrified depth shadows.",
"in dynamic battle pose. A majestic evolved tiger spirit mid-lightning-pounce, immense powerful form with pristine white and silver fur, bold black stripes crackling with blazing electric-gold lightning, large blazing amber-gold eyes with electric-white ring, golden thunder fang jaw ornaments, golden arc earrings, golden thunderbolt medallion bouncing, dynamic mid-air pounce with both front paws extended with visible lightning bolts arcing from the claws, magnificent electric mane streaming, thick tail fully electrified, body surging with overwhelming thunder power, mouth wide in a thunderclap roar, supreme predator fury, subtle warm depth shadows enhancing three-dimensionality."),

(16,"灵麒","spirit_qilin","SSR","心","兽灵族","qilin spirit fawn",
"A young qilin (Chinese unicorn) spirit fawn, delicate body with iridescent fur shifting between soft lavender, rose-pink, and pale gold, ink wash brush texture showing volume through tonal shading, a small single horn on the forehead glowing with gentle pink-gold light, large wise amethyst-purple eyes with a warm compassionate expression, scale-like patterns along the cheeks in soft rainbow pastel hues, small deer-like ears with pink-gold tips, a tiny heart-shaped rose-quartz bead on a silk cord at the neck, gentle benevolent aura, subtle warm rainbow-tinted shadows giving ethereal depth.",
"A young qilin spirit fawn in gentle battle stance, delicate body with iridescent fur shifting between soft lavender, rose-pink, and pale gold, ink wash brush strokes showing volume, a small single horn on the forehead glowing pink-gold, large wise amethyst-purple eyes with calm determined gaze, scale-like patterns along the body in soft rainbow pastel hues, standing in an elegant poised stance, slender legs with hoof-like feet, a flowing tail with iridescent rainbow tip, heart-shaped rose-quartz bead at neck, body radiating gentle warmth, serene yet powerful holy beast presence, subtle warm rainbow-tinted shadows under the body.",
"A majestic evolved qilin spirit, magnificent form with luminous iridescent fur in rich lavender, rose, gold, and soft teal with flowing ink wash texture, a grand single horn now longer and radiating rainbow-prismatic light, large blazing amethyst-purple eyes with a golden-pink heart-shaped ring in the pupil radiating divine benevolence, elaborate rainbow scale patterns along the face and neck, delicate golden filigree ornaments at the horn base, small ears adorned with tiny heart-shaped golden earrings, an ornate rainbow jade pendant in golden setting on a silk cord, absolute holy beast majesty, subtle warm prismatic depth shadows.",
"in dynamic battle pose. A majestic evolved qilin spirit in divine stance, magnificent form with luminous iridescent fur in rich lavender, rose, gold, and soft teal, grand single horn radiating rainbow-prismatic light, large blazing amethyst-purple eyes with golden-pink heart ring, elaborate rainbow scale patterns across the body, golden filigree horn ornaments, heart-shaped golden earrings, rainbow jade pendant floating, dynamic rearing pose with front hooves raised high, rainbow energy cascading from the horn, flowing mane and tail streaming with prismatic colors, body enveloped in gentle divine radiance, compassionate yet devastatingly powerful expression, subtle warm prismatic depth shadows enhancing three-dimensionality."),
]

# We'll load the rest of the pets from a data string to keep the script manageable
# For pets 17-236, we use a more compact format and auto-generate consistent prompts

# Helper: generate 4 prompts from compact data
def gen_prompts_from_compact(num, cn, pid, rarity, elem, race, creature,
                              body_colors, features_normal, eye_desc, accessory_normal,
                              battle_pose_normal, 
                              awaken_body, awaken_face_pattern, awaken_eye_ring, awaken_accessories, awaken_expression,
                              awaken_battle_pose, awaken_battle_features):
    """Generate 4 prompts from compact description data."""
    nav = f"A young {creature}, {body_colors}, ink wash brush texture showing volume through tonal shading, {features_normal}, {eye_desc}, {accessory_normal}, subtle warm shadow under the chin giving depth."
    nfl = f"A young {creature} in battle-ready stance, {body_colors}, ink wash brush strokes showing volume through tonal variation, {features_normal}, {eye_desc.replace('expression', 'gaze').replace('curious', 'determined').replace('cheerful', 'alert').replace('playful', 'fierce')}, {battle_pose_normal}, subtle warm shadows under the belly giving depth."
    aav = f"A majestic evolved {creature}, {awaken_body}, {awaken_face_pattern}, large blazing eyes with {awaken_eye_ring} ring in the pupil radiating mastery, {awaken_accessories}, {awaken_expression}, subtle warm depth shadows."
    afl = f"in dynamic battle pose. A majestic evolved {creature} mid-attack, {awaken_body}, {awaken_face_pattern}, large blazing eyes with {awaken_eye_ring} ring, {awaken_accessories}, {awaken_battle_pose}, {awaken_battle_features}, subtle warm depth shadows enhancing three-dimensionality."
    return nav, nfl, aav, afl


# We'll write the remaining pets inline in the data file for completeness.
# For now, write the pets we have in the PETS array and generate a programmatic template for the rest.

def write_doc():
    f = open(OUTPUT, "w", encoding="utf-8")
    f.write("# 《灵宠放置传》宠物美术资源提示词 v3\n\n")
    f.write("> 基于宠物设计和合成方案 v3，共 236 只宠物 × 4 变体 = 944 个提示词\n")
    f.write("> 每只宠物包含：normal_avatar (128×128)、normal_full (512×512)、awakened_avatar (128×128)、awakened_full (512×512)\n>\n")
    f.write("> **v3 提示词改进**：\n")
    f.write("> 1. 严禁任何文字/符文/符号出现\n")
    f.write("> 2. 水墨风格增加立体感（墨色浓淡变化营造体积感）\n")
    f.write("> 3. 配色活泼多样，不再单一使用元素主色\n\n---\n\n")

    current_race = ""
    for pet in PETS:
        num, cn, pid, rarity, elem, race, creature, nav_d, nfl_d, aav_d, afl_d = pet
        
        # Race header
        if race != current_race:
            current_race = race
            f.write(f"\n## {race}\n\n---\n\n")
        
        f.write(f"### #{num} {cn} ({pid}) — {rarity} · {elem} · {race}\n\n")
        
        # normal_avatar
        f.write(f"**normal_avatar** (`prompt_{pid}_normal_avatar.txt`):\n")
        f.write(f"```\n{S_AV} {F_N} {nav_d} {R_AV}\n```\n\n")
        
        # normal_full
        f.write(f"**normal_full** (`prompt_{pid}_normal_full.txt`):\n")
        f.write(f"```\n{S_FL} {F_N} {nfl_d} {R_FL}\n```\n\n")
        
        # awakened_avatar
        f.write(f"**awakened_avatar** (`prompt_{pid}_awakened_avatar.txt`):\n")
        f.write(f"```\n{S_AA} {F_A} {aav_d} {R_AV}\n```\n\n")
        
        # awakened_full
        f.write(f"**awakened_full** (`prompt_{pid}_awakened_full.txt`):\n")
        f.write(f"```\n{S_AF} {F_A} {afl_d} {R_FL}\n```\n\n---\n\n")
    
    f.close()
    print(f"Written {len(PETS)} pets to {OUTPUT}")
    print(f"Total prompts: {len(PETS) * 4}")

write_doc()
